/**
 * Normalizes event config JSON to ensure all sections exist with defaults.
 * Prevents runtime errors from optional chaining on incomplete configs
 * (e.g., events created before certain sections were added).
 */
function ensureConfigDefaults(cfg) {
  if (!cfg || typeof cfg !== 'object') cfg = {};

  return {
    envelope: {
      enabled: false,
      template: 'envelope',
      style: 'classic',
      sealStyle: 'wax-circle',
      envelopeColor: '#1a1a2e',
      sealColor: '#8b0000',
      sealText: '♡',
      sealImage: '',
      instructionText: 'Toca para abrir',
      bgColor: '#0a0a14',
      bgColor2: '#1a1a2e',
      textColor: 'rgba(255,255,255,0.5)',
      ...(cfg.envelope || {}),
    },
    intro: {
      enabled: cfg.intro?.enabled ?? true,
      background: cfg.intro?.background || '',
      phrase: cfg.intro?.phrase || '',
      duration: cfg.intro?.duration || 4,
      videoStart: cfg.intro?.videoStart,
      videoEnd: cfg.intro?.videoEnd,
      videoDuration: cfg.intro?.videoDuration,
      phraseStyle: {
        fontFamily: 'script',
        fontSize: 42,
        color: '#d4a017',
        fontWeight: 400,
        ...(cfg.intro?.phraseStyle || {}),
      },
      particles: {
        enabled: true,
        type: 'sparkles',
        color1: '#d4a017',
        color2: '#ffffff',
        direction: 'up',
        quantity: 20,
        speed: 5,
        size: 4,
        opacity: 0.8,
        ...(cfg.intro?.particles || {}),
      },
    },
    hero: {
      backgroundGif: cfg.hero?.backgroundGif || '',
      audioUrl: cfg.hero?.audioUrl || '',
      eventDescription: cfg.hero?.eventDescription || '',
      celebrantNames: cfg.hero?.celebrantNames || '',
      showCelebrantNames: cfg.hero?.showCelebrantNames !== false,
      heroPhrase: cfg.hero?.heroPhrase || '',
      showDescription: cfg.hero?.showDescription || false,
      description: cfg.hero?.description || '',
      countdownDate: cfg.hero?.countdownDate || '',
      countdownShowCardBg: cfg.hero?.countdownShowCardBg,
      countdownCardBorderRadius: cfg.hero?.countdownCardBorderRadius,
      eventDescriptionStyle: {
        fontFamily: 'sans',
        fontSize: 22,
        color1: '#ffffff',
        color2: '',
        gradientAngle: 135,
        gradientIntensity: 50,
        fontWeight: 400,
        ...(cfg.hero?.eventDescriptionStyle || {}),
      },
      celebrantNamesStyle: {
        fontFamily: 'script',
        fontSize: 80,
        color1: '#d4a017',
        color2: '#b8860b',
        gradientAngle: 135,
        gradientIntensity: 50,
        fontWeight: 400,
        ...(cfg.hero?.celebrantNamesStyle || {}),
      },
      heroPhraseStyle: {
        fontFamily: 'serif',
        fontSize: 16,
        color: '#ffffff',
        ...(cfg.hero?.heroPhraseStyle || {}),
      },
    },
    invitation: {
      title: cfg.invitation?.title || 'Están cordialmente invitados',
      subtitle: cfg.invitation?.subtitle || '',
      showCardBg: cfg.invitation?.showCardBg,
      cardBorderRadius: cfg.invitation?.cardBorderRadius,
      sectionStyle: cfg.invitation?.sectionStyle,
    },
    details: {
      enabled: cfg.details?.enabled ?? true,
      title: cfg.details?.title || 'Detalles del Evento',
      showCardBg: cfg.details?.showCardBg,
      cardBorderRadius: cfg.details?.cardBorderRadius,
      cards: cfg.details?.cards || [],
      sectionStyle: cfg.details?.sectionStyle,
    },
    venues: {
      enabled: cfg.venues?.enabled ?? true,
      iconStyle: cfg.venues?.iconStyle || 'circle',
      showCardBg: cfg.venues?.showCardBg,
      cardBorderRadius: cfg.venues?.cardBorderRadius,
      items: cfg.venues?.items || [],
      sectionStyle: cfg.venues?.sectionStyle,
    },
    itinerary: {
      enabled: cfg.itinerary?.enabled ?? true,
      title: cfg.itinerary?.title || 'Itinerario',
      showCardBg: cfg.itinerary?.showCardBg,
      cardBorderRadius: cfg.itinerary?.cardBorderRadius,
      items: cfg.itinerary?.items || [],
      sectionStyle: cfg.itinerary?.sectionStyle,
    },
    gallery: {
      enabled: cfg.gallery?.enabled ?? true,
      title: cfg.gallery?.title || 'Galería',
      description: cfg.gallery?.description || '',
      displayStyle: cfg.gallery?.displayStyle || 'carousel-3d',
      sectionStyle: cfg.gallery?.sectionStyle,
    },
    dresscode: {
      enabled: cfg.dresscode?.enabled ?? true,
      title: cfg.dresscode?.title || 'Código de Vestimenta',
      description: cfg.dresscode?.description || '',
      showCardBg: cfg.dresscode?.showCardBg,
      cardBorderRadius: cfg.dresscode?.cardBorderRadius,
      sectionIcon: cfg.dresscode?.sectionIcon,
      cards: cfg.dresscode?.cards || [],
      sectionStyle: cfg.dresscode?.sectionStyle,
    },
    gifts: {
      enabled: cfg.gifts?.enabled ?? true,
      title: cfg.gifts?.title || 'Mesa de Regalos',
      description: cfg.gifts?.description || '',
      link: cfg.gifts?.link || '',
      buttonText: cfg.gifts?.buttonText || 'Ver Lista',
      showCardBg: cfg.gifts?.showCardBg,
      cardBorderRadius: cfg.gifts?.cardBorderRadius,
      sectionIcon: cfg.gifts?.sectionIcon,
      sectionStyle: cfg.gifts?.sectionStyle,
      transfer: {
        enabled: false,
        title: '¿Prefieres hacer una transferencia?',
        description: '',
        accountName: '',
        bank: '',
        accountType: 'tarjeta',
        accountNumber: '',
        animation: 'coins',
        ...(cfg.gifts?.transfer || {}),
      },
    },
    rsvp: {
      enabled: cfg.rsvp?.enabled ?? true,
      title: cfg.rsvp?.title || 'Confirmar Asistencia',
      showCardBg: cfg.rsvp?.showCardBg,
      cardBorderRadius: cfg.rsvp?.cardBorderRadius,
      sectionIcon: cfg.rsvp?.sectionIcon,
      registrationFields: cfg.rsvp?.registrationFields,
      sectionStyle: cfg.rsvp?.sectionStyle,
    },
    theme: {
      cardBg: 'rgba(255,255,255,0.05)',
      cardBorder: 'rgba(212,160,23,0.3)',
      textPrimary: '#ffffff',
      textPrimaryFont: '',
      textSecondary: 'rgba(255,255,255,0.7)',
      textSecondaryFont: '',
      navFooterText: '#d4a017',
      navFooterFont: '',
      buttonBg: '#d4a017',
      buttonText: '#1a1a2e',
      buttonFont: '',
      landingBgTexture: 'none',
      scrollAnimation: 'fade-up',
      ...(cfg.theme || {}),
    },
    globalStyles: {
      sectionHeadingStyle: {
        fontFamily: 'script',
        fontSize: 36,
        color: '#d4a017',
        ...(cfg.globalStyles?.sectionHeadingStyle || {}),
      },
      titleStyle: {
        fontFamily: 'script',
        fontSize: 42,
        color: '#d4a017',
        color2: '#f0c040',
        gradientAngle: 135,
        gradientIntensity: 50,
        fontWeight: 400,
        ...(cfg.globalStyles?.titleStyle || {}),
      },
      subtitleStyle: {
        fontFamily: 'sans',
        fontSize: 16,
        color: '#ffffffb3',
        ...(cfg.globalStyles?.subtitleStyle || {}),
      },
      contentStyle: {
        fontFamily: 'sans',
        fontSize: 14,
        color: '#ffffffb3',
        ...(cfg.globalStyles?.contentStyle || {}),
      },
      separatorStyle: {
        type: 'elegant',
        color: '#d4a017',
        ...(cfg.globalStyles?.separatorStyle || {}),
      },
    },
    // Preserve favicon if set
    favicon: cfg.favicon || undefined,
  };
}

module.exports = { ensureConfigDefaults };
